### ISSUE TITLE
`product_get_cost_field` and `stock` both use "Cost price" to name different fields

### ISSUE THREAD

**Issue by clonedagain** [OCA/margin-analysis#6]
As a workaround for https://github.com/odoo/odoo/issues/3396, I think the module `product_get_cost_field` should change the label of `product.product.standard_price` to something else but "Cost price", to make it clear what each field does.

PS: as it turns out, the wording in standard module `stock` is probably right and `product_get_cost_field` should not add a field labeled "Standard Price".
To avoid breaking existing installations, in the short term the field `cost_price` should be relabeled to another name.
In the longer term, we should strive to integrate `product_get_cost_field`'s features deeper into the standard costing features.

**Comment by clonedagain** [comment]
You can assign this to me unless someone objects to it.

**Comment by yvaucher** [comment]
This module was developed to know the cost of a product to make margin analysis. So cost price seems suited. Maybe as you said we need 2 different fields. For inventory valuation, the price might be different than purchase price.

I would prefer a name like 'inventory_value' as 'value' seems too generic.

**Comment by clonedagain** [comment]
Yes sorry if this is not clear, I'm proposing to rename the standard's 
`standard_price` to "Value" (or "Inventory Value", it sounds better indeed).
`cost_price` must indeed be named "Cost Price".

**Comment by clonedagain** [comment]
From https://github.com/odoo/odoo/issues/3396#issuecomment-61172164 I gather that the change must be made the other way round: Cost Price is the right term for inventory valuation, and we have to name our field something else.

**Comment by clonedagain** [comment]
@yvaucher can you think of another name instead of "cost price" for OCA's module?

**Comment by clonedagain** [comment]
After reading a bit more on the subject, I'm not quite sure we really should have 2 fields.
For example in the classic book "Gestion industrielle", Blondel writes:
"La logique économique et les règles fiscales impliquent la comptabilisation de coûts lorsqu’ils ont été constatés. ... Le mode de valorisation des composants n’est pas neutre sur la structure de coût de revient. Il sera cohérent avec la méthode adoptée pour la valorisation des stocks"
(rough translation: Economic logic and the tax rules involve cost accounting when they are recorded. ... The valuation mode of components is not neutral on the structure of cost. It will be consistent with the method adopted for the valuation of stocks)

So having 2 distinct fields may actually be bad practice, if not downright forbidden.

So how about we change `product_cost_incl_bom` to simply make it a new "costing method" called "production cost" to compute product.standard_price using the BOM, in the same drop-down menu as "standard price" and "average price"? `product_get_cost_field` would then be superfluous.
This way, for raw materials you could choose "average price", and for manufactured products you would chose "production cost"

**Comment by gdgellatly** [comment]
Hi,

The way I would and do handle this issue is not to create a new costing method.

The premise is this. Average, FIFO, Actual and Standard costs is all you need.  What you really want to do, is ensure that when goods are manufactured the correct accounting operations are applied and inventory costs updated if needed.

It's been a while since I looked at the code, but the methodology is pretty straight forward.

Generally speaking a BoM is made up of some costs, raw materials, direct labour and maybe some overhead allocation.  Each raw material may use a different costing method.  Personally I avoid getting too complicated on the rest and tend to use Goldratts methodology which is "Only those costs that are truly variable should be counted."   For most businesses labour and overheads are not truly variable and count the other costs still "above the line" but not as part of inventory cost..  But in any case it isn't hard to include them.  If I was to include those 2 it would use standard cost, but there is no reason it has to be.  All that matters is that you can determine your cost from a BoM or MO.

If I am using standard cost for the produced product.  Then I take the standard cost.

If I am using any other method then it is the sum of those bom components by whatever costing method those components use (i.e. cost price field) to create an aggregate cost, divided by the number of units produced as the input.

Then it does not matter costing method, the rest is automatically handled.  If its average, it gets updated (although from memory you need to extend manufacturing to update average) It also then doesn't matter if sometimes you buy it, sometimes you make it.

The only thing you need to handle is the calculation for what cost goes in, which is at the point of processing production.  Get it right there and then everything else works.

**Comment by clonedagain** [comment]
Le 02/11/2014 23:45, Graeme Gellatly a écrit :

> The way I would and do handle this issue is not to create a new 
> costing method.
> 
> The premise is this. Average, FIFO, Actual and Standard costs is all 
> you need. (...)
> 
> I'm ready to trust you on this, but in Odoo:
> - FIFO and actual are not implemented
> - standard cost means "manual entry" (not computed), is that what you 
>   mean too?

Then if I understand what you mean, what we should really do is hack 
into the existing "costing methods" (currently only "average"), which 
currently work on purchase orders only, and extend them to manufacturing 
orders using the cost of the BOM (components costs+cost of manufacturing 
operations) instead of the purchase price. Is that it?

Lionel Sausin.

**Comment by gdgellatly** [comment]
You got it.

Tomorrow when I get to work I'll dig out the relevant code and post as
reference. It will show the insertion points and i think the methods you
guys have been discussing could be good extensions to the calculations.

I get lost with odoo about what cost methods are in core in different
versions.

Yes, standard cost gets used a lot in manufacturing inputs and outputs as
often it is just an estimate of allocation.

Actual cost is really simple to implement using production lots and storing
a cost against it. 50 lines of code and in production for years with very
few issues. I have published it somewhere once maybe as a merge proposal
but never looked at since. It just works, although it requires prod lots
everywhere.

I thought fifo was a cost method now. I wrote a fifo module once but it
never behaved properly and I never needed so I abandoned it.

**Comment by clonedagain** [comment]
@gdgellatly OK thanks. I'm looking forward to your pointers. I fear it's going to be pretty messy in v7, maybe less in v8...
A bit off-topic, but costing based on production lots is on my roadmap too, so if you care to share your module I'll be glad to test it and help you push it to OCA.

**Comment by gdgellatly** [comment]
https://github.com/gdgellatly/odoo_public/blob/7.0/stock_alternative_costing/stock_cost.py

I had to refactor a bit, was a port from when I used different costing methods and found quite a bit of useless code in there, but cleaned it up to explain the point and allow extension.  In regards to the prodlot stuff, I'll find it and post later.  I actually ended up deprecating it for v7 because the original business process that required it ceased to exist.

**Comment by clonedagain** [comment]
@gdgellatly thanks for sharing this, it looks decently simple indeed.
I'm sure your module and the existing OCA modules here can be merged - maybe targeting v8 to avoid breaking existing installations.
But I can't afford to go this deep into the matter right now, my short-term objectives have a limited scope.

So what I propose right now is simply to relabel `cost_price` as "Manufacturing cost" in `product_get_cost_field`.
Would everyone agree with this?
